# Generated by Django 2.2.2 on 2019-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_id', models.CharField(max_length=4)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.RenameModel(
            old_name='BreedDescription',
            new_name='Description',
        ),
    ]
