# Generated by Django 2.2.2 on 2019-06-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0002_auto_20190626_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
