# Generated by Django 2.2.2 on 2019-06-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0003_auto_20190626_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='id',
        ),
        migrations.AlterField(
            model_name='description',
            name='breed_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='breed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catapp.Description'),
        ),
    ]
