# Generated by Django 2.2.2 on 2019-06-27 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0004_auto_20190626_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='img_file',
        ),
        migrations.AddField(
            model_name='image',
            name='img_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
