# Generated by Django 2.2.2 on 2019-06-28 08:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0005_auto_20190627_1625'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='description',
            managers=[
                ('cats_descriptions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('cats_pics', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_file',
        ),
    ]
